version: '3'
services:
  flask_app:
    image: shaykekeidar/elisra-task-one:latest
    container_name: flask_app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - "5000"

  nginx_proxy:
    image: shaykekeidar/elisra-task-two:latest
    container_name: nginx_proxy
    ports:
      - "8081:80"
    depends_on:
      - flask_app